# Generated by Django 3.0.8 on 2020-11-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsedfile',
            old_name='submit_count',
            new_name='submit_number',
        ),
        migrations.AddField(
            model_name='participation',
            name='submit_count',
            field=models.IntegerField(default=0, verbose_name='제출 횟수'),
        ),
    ]
