# Generated by Django 3.0.8 on 2020-11-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20201122_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedfile',
            name='grade_date',
            field=models.DateField(auto_now=True, verbose_name='평가 날짜'),
        ),
    ]
