# Generated by Django 3.0.8 on 2020-11-23 02:01

import collect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_parsedfile_grade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedfile',
            name='grading_score',
            field=models.IntegerField(blank=True, null=True, validators=[collect.models.grading_score_validator], verbose_name='평가 점수'),
        ),
    ]
